# Generated by Django 5.0 on 2023-12-14 09:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_start",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            14,
                            9,
                            16,
                            13,
                            231160,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("time_end", models.DateTimeField(blank=True, null=True)),
                ("time", models.DurationField(blank=True, null=True)),
                ("is_work", models.BooleanField(default=True)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-time_start",),
            },
        ),
    ]
