# Generated by Django 5.0 on 2023-12-14 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="time_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
